# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\es-sde.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1370, 853)
        MainWindow.setMinimumSize(QtCore.QSize(1370, 704))
        MainWindow.setStyleSheet("    font-family: SCG;\n"
"    font-size:15pt;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.big_menu = QtWidgets.QFrame(self.centralwidget)
        self.big_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.big_menu.setStyleSheet("background-color:    #222222;\n"
"border-radius: 0px;\n"
"padding: 0px 0px;")
        self.big_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.big_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.big_menu.setObjectName("big_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.big_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.big_menu_btn = QtWidgets.QPushButton(self.big_menu)
        self.big_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/assets/SDE-Logo-Login_mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_menu_btn.setIcon(icon)
        self.big_menu_btn.setIconSize(QtCore.QSize(150, 150))
        self.big_menu_btn.setCheckable(True)
        self.big_menu_btn.setObjectName("big_menu_btn")
        self.gridLayout_3.addWidget(self.big_menu_btn, 2, 1, 1, 1)
        self.big_db_btn = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_db_btn.setFont(font)
        self.big_db_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_db_btn.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/assets/document-2-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_db_btn.setIcon(icon1)
        self.big_db_btn.setIconSize(QtCore.QSize(25, 25))
        self.big_db_btn.setCheckable(True)
        self.big_db_btn.setChecked(True)
        self.big_db_btn.setObjectName("big_db_btn")
        self.gridLayout_3.addWidget(self.big_db_btn, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 1, 1, 1)
        self.big_insign_bt = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_insign_bt.setFont(font)
        self.big_insign_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_insign_bt.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/assets/box-3-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_insign_bt.setIcon(icon2)
        self.big_insign_bt.setIconSize(QtCore.QSize(25, 25))
        self.big_insign_bt.setCheckable(True)
        self.big_insign_bt.setChecked(True)
        self.big_insign_bt.setObjectName("big_insign_bt")
        self.gridLayout_3.addWidget(self.big_insign_bt, 5, 1, 1, 1)
        self.big_controller_btn = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_controller_btn.setFont(font)
        self.big_controller_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_controller_btn.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/assets/chip-2-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_controller_btn.setIcon(icon3)
        self.big_controller_btn.setIconSize(QtCore.QSize(25, 25))
        self.big_controller_btn.setCheckable(True)
        self.big_controller_btn.setChecked(True)
        self.big_controller_btn.setObjectName("big_controller_btn")
        self.gridLayout_3.addWidget(self.big_controller_btn, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.big_menu, 0, 1, 1, 1)
        self.mini_menu = QtWidgets.QFrame(self.centralwidget)
        self.mini_menu.setMaximumSize(QtCore.QSize(75, 16777215))
        self.mini_menu.setStyleSheet("background-color:    #222222;\n"
"border-radius: 0px;\n"
"padding: 0px 0px;")
        self.mini_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mini_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mini_menu.setObjectName("mini_menu")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mini_menu)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 0, 1, 1)
        self.mini_db_btn = QtWidgets.QPushButton(self.mini_menu)
        self.mini_db_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini_db_btn.setStyleSheet("QPushButton {\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        self.mini_db_btn.setText("")
        self.mini_db_btn.setIcon(icon1)
        self.mini_db_btn.setIconSize(QtCore.QSize(25, 25))
        self.mini_db_btn.setCheckable(True)
        self.mini_db_btn.setChecked(True)
        self.mini_db_btn.setObjectName("mini_db_btn")
        self.gridLayout_4.addWidget(self.mini_db_btn, 4, 0, 1, 1)
        self.mini_insign_bt = QtWidgets.QPushButton(self.mini_menu)
        self.mini_insign_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini_insign_bt.setStyleSheet("QPushButton {\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        self.mini_insign_bt.setText("")
        self.mini_insign_bt.setIcon(icon2)
        self.mini_insign_bt.setIconSize(QtCore.QSize(25, 25))
        self.mini_insign_bt.setCheckable(True)
        self.mini_insign_bt.setChecked(True)
        self.mini_insign_bt.setObjectName("mini_insign_bt")
        self.gridLayout_4.addWidget(self.mini_insign_bt, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.mini_controller_btn = QtWidgets.QPushButton(self.mini_menu)
        self.mini_controller_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini_controller_btn.setStyleSheet("QPushButton {\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        self.mini_controller_btn.setText("")
        self.mini_controller_btn.setIcon(icon3)
        self.mini_controller_btn.setIconSize(QtCore.QSize(25, 25))
        self.mini_controller_btn.setCheckable(True)
        self.mini_controller_btn.setChecked(True)
        self.mini_controller_btn.setObjectName("mini_controller_btn")
        self.gridLayout_4.addWidget(self.mini_controller_btn, 3, 0, 1, 1)
        self.mini_menu_btn = QtWidgets.QPushButton(self.mini_menu)
        self.mini_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini_menu_btn.setStyleSheet("padding: 10px 10px;")
        self.mini_menu_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/assets/menu-4-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mini_menu_btn.setIcon(icon4)
        self.mini_menu_btn.setIconSize(QtCore.QSize(20, 20))
        self.mini_menu_btn.setCheckable(True)
        self.mini_menu_btn.setObjectName("mini_menu_btn")
        self.gridLayout_4.addWidget(self.mini_menu_btn, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mini_menu, 0, 0, 1, 1)
        self.main_page = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_page.setEnabled(True)
        self.main_page.setMinimumSize(QtCore.QSize(1000, 20))
        self.main_page.setTabletTracking(False)
        self.main_page.setAcceptDrops(False)
        self.main_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_page.setAutoFillBackground(False)
        self.main_page.setObjectName("main_page")
        self.controller_page = QtWidgets.QWidget()
        self.controller_page.setObjectName("controller_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.controller_page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.controller_page)
        self.frame_2.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sensorRangeView = QtWidgets.QTableView(self.frame_2)
        self.sensorRangeView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorRangeView.sizePolicy().hasHeightForWidth())
        self.sensorRangeView.setSizePolicy(sizePolicy)
        self.sensorRangeView.setMaximumSize(QtCore.QSize(520, 100))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.sensorRangeView.setFont(font)
        self.sensorRangeView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sensorRangeView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.sensorRangeView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.sensorRangeView.setAlternatingRowColors(True)
        self.sensorRangeView.setObjectName("sensorRangeView")
        self.gridLayout_6.addWidget(self.sensorRangeView, 1, 0, 1, 1)
        self.devicesTableView = QtWidgets.QTableView(self.frame_2)
        self.devicesTableView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesTableView.sizePolicy().hasHeightForWidth())
        self.devicesTableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.devicesTableView.setFont(font)
        self.devicesTableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.devicesTableView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.devicesTableView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.devicesTableView.setAlternatingRowColors(True)
        self.devicesTableView.setObjectName("devicesTableView")
        self.gridLayout_6.addWidget(self.devicesTableView, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flashStatusLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.flashStatusLabel.setFont(font)
        self.flashStatusLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel.setObjectName("flashStatusLabel")
        self.horizontalLayout.addWidget(self.flashStatusLabel)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:black;")
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 4, 0, 1, 1)
        self.serial_monitor = QtWidgets.QTextEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.serial_monitor.setFont(font)
        self.serial_monitor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.serial_monitor.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"color:#1c305c;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.serial_monitor.setReadOnly(True)
        self.serial_monitor.setObjectName("serial_monitor")
        self.gridLayout_6.addWidget(self.serial_monitor, 5, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addGoodDeviceButton = QtWidgets.QPushButton(self.frame_2)
        self.addGoodDeviceButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.addGoodDeviceButton.setFont(font)
        self.addGoodDeviceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addGoodDeviceButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.addGoodDeviceButton.setWhatsThis("")
        self.addGoodDeviceButton.setStyleSheet("QPushButton {\n"
"    background-color: #02d2f5; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ac1dd; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2eb3ca; /* Even Darker Green when pressed */\n"
"}")
        self.addGoodDeviceButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/assets/eye-2-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addGoodDeviceButton.setIcon(icon5)
        self.addGoodDeviceButton.setIconSize(QtCore.QSize(35, 35))
        self.addGoodDeviceButton.setAutoRepeatInterval(101)
        self.addGoodDeviceButton.setObjectName("addGoodDeviceButton")
        self.verticalLayout_2.addWidget(self.addGoodDeviceButton)
        self.clearListButton = QtWidgets.QPushButton(self.frame_2)
        self.clearListButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clearListButton.setFont(font)
        self.clearListButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearListButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.clearListButton.setWhatsThis("")
        self.clearListButton.setStyleSheet("QPushButton {\n"
"    background-color: #02d2f5; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ac1dd; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2eb3ca; /* Even Darker Green when pressed */\n"
"}")
        self.clearListButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/assets/delete-property-64 (2).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearListButton.setIcon(icon6)
        self.clearListButton.setIconSize(QtCore.QSize(35, 35))
        self.clearListButton.setAutoRepeatInterval(101)
        self.clearListButton.setObjectName("clearListButton")
        self.verticalLayout_2.addWidget(self.clearListButton)
        self.printNowButton = QtWidgets.QPushButton(self.frame_2)
        self.printNowButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.printNowButton.setFont(font)
        self.printNowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.printNowButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.printNowButton.setWhatsThis("")
        self.printNowButton.setStyleSheet("QPushButton {\n"
"    background-color: #02d2f5; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ac1dd; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2eb3ca; /* Even Darker Green when pressed */\n"
"}")
        self.printNowButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/assets/printer-64 (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printNowButton.setIcon(icon7)
        self.printNowButton.setIconSize(QtCore.QSize(35, 35))
        self.printNowButton.setAutoRepeatInterval(101)
        self.printNowButton.setObjectName("printNowButton")
        self.verticalLayout_2.addWidget(self.printNowButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(2, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 2, 0, 1, 4)
        self.frame = QtWidgets.QFrame(self.controller_page)
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ap_enable = QtWidgets.QCheckBox(self.frame)
        self.ap_enable.setGeometry(QtCore.QRect(10, 177, 121, 41))
        self.ap_enable.setStyleSheet("color:white;")
        self.ap_enable.setObjectName("ap_enable")
        self.uart_portBox = QtWidgets.QComboBox(self.frame)
        self.uart_portBox.setGeometry(QtCore.QRect(10, 309, 201, 31))
        self.uart_portBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.uart_portBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uart_portBox.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.uart_portBox.setObjectName("uart_portBox")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 265, 91, 52))
        self.label_12.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 108, 71, 31))
        self.label_13.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:white;")
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 191, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_2.setObjectName("label_2")
        self.inspec_enable = QtWidgets.QCheckBox(self.frame)
        self.inspec_enable.setGeometry(QtCore.QRect(10, 146, 171, 31))
        self.inspec_enable.setStyleSheet("color:white;")
        self.inspec_enable.setTristate(False)
        self.inspec_enable.setObjectName("inspec_enable")
        self.powerOnButton = QtWidgets.QPushButton(self.frame)
        self.powerOnButton.setGeometry(QtCore.QRect(110, 108, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.powerOnButton.setFont(font)
        self.powerOnButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerOnButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.powerOnButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.powerOnButton.setCheckable(True)
        self.powerOnButton.setChecked(False)
        self.powerOnButton.setAutoRepeat(False)
        self.powerOnButton.setObjectName("powerOnButton")
        self.powerOffButton = QtWidgets.QPushButton(self.frame)
        self.powerOffButton.setGeometry(QtCore.QRect(110, 108, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.powerOffButton.setFont(font)
        self.powerOffButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerOffButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.powerOffButton.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.powerOffButton.setCheckable(True)
        self.powerOffButton.setChecked(False)
        self.powerOffButton.setAutoRepeat(False)
        self.powerOffButton.setAutoExclusive(False)
        self.powerOffButton.setObjectName("powerOffButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 249, 191, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_14.setObjectName("label_14")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(10, 229, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(10, 351, 91, 31))
        self.label_27.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color:white;")
        self.label_27.setObjectName("label_27")
        self.serial_r = QtWidgets.QPushButton(self.frame)
        self.serial_r.setGeometry(QtCore.QRect(110, 351, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.serial_r.setFont(font)
        self.serial_r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.serial_r.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.serial_r.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.serial_r.setCheckable(True)
        self.serial_r.setChecked(False)
        self.serial_r.setAutoRepeat(False)
        self.serial_r.setObjectName("serial_r")
        self.serial_s = QtWidgets.QPushButton(self.frame)
        self.serial_s.setGeometry(QtCore.QRect(110, 351, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.serial_s.setFont(font)
        self.serial_s.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.serial_s.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.serial_s.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.serial_s.setCheckable(True)
        self.serial_s.setChecked(False)
        self.serial_s.setAutoRepeat(False)
        self.serial_s.setObjectName("serial_s")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(10, 424, 191, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_15.setObjectName("label_15")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(10, 404, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_29.setObjectName("label_29")
        self.boxlot_Box = QtWidgets.QComboBox(self.frame)
        self.boxlot_Box.setGeometry(QtCore.QRect(10, 60, 201, 31))
        self.boxlot_Box.setMaximumSize(QtCore.QSize(16777215, 40))
        self.boxlot_Box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boxlot_Box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"    font-size:12pt;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.boxlot_Box.setObjectName("boxlot_Box")
        self.error_point_Box = QtWidgets.QComboBox(self.frame)
        self.error_point_Box.setGeometry(QtCore.QRect(10, 500, 201, 40))
        self.error_point_Box.setMaximumSize(QtCore.QSize(16777215, 40))
        self.error_point_Box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.error_point_Box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.error_point_Box.setObjectName("error_point_Box")
        self.RejectButton = QtWidgets.QPushButton(self.frame)
        self.RejectButton.setGeometry(QtCore.QRect(10, 550, 201, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.RejectButton.setFont(font)
        self.RejectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RejectButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.RejectButton.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.RejectButton.setCheckable(True)
        self.RejectButton.setChecked(False)
        self.RejectButton.setAutoRepeat(False)
        self.RejectButton.setAutoExclusive(False)
        self.RejectButton.setObjectName("RejectButton")
        self.error_type_box = QtWidgets.QComboBox(self.frame)
        self.error_type_box.setGeometry(QtCore.QRect(10, 453, 201, 40))
        self.error_type_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(12)
        self.error_type_box.setFont(font)
        self.error_type_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.error_type_box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"    font-size:12pt;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.error_type_box.setObjectName("error_type_box")
        self.error_type_box.addItem("")
        self.error_type_box.addItem("")
        self.error_type_box.addItem("")
        self.serial_s.raise_()
        self.powerOnButton.raise_()
        self.label_2.raise_()
        self.ap_enable.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.inspec_enable.raise_()
        self.powerOffButton.raise_()
        self.label_14.raise_()
        self.label_27.raise_()
        self.serial_r.raise_()
        self.label_26.raise_()
        self.label_3.raise_()
        self.uart_portBox.raise_()
        self.label_15.raise_()
        self.label_29.raise_()
        self.boxlot_Box.raise_()
        self.error_point_Box.raise_()
        self.RejectButton.raise_()
        self.error_type_box.raise_()
        self.gridLayout_7.addWidget(self.frame, 1, 4, 2, 1)
        self.label = QtWidgets.QLabel(self.controller_page)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 5)
        self.programFileComboBox = QtWidgets.QComboBox(self.controller_page)
        self.programFileComboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.programFileComboBox.setFont(font)
        self.programFileComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.programFileComboBox.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.programFileComboBox.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.programFileComboBox.setObjectName("programFileComboBox")
        self.gridLayout_7.addWidget(self.programFileComboBox, 1, 0, 1, 2)
        self.eraseButton = QtWidgets.QPushButton(self.controller_page)
        self.eraseButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.eraseButton.setFont(font)
        self.eraseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eraseButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.eraseButton.setStyleSheet("QPushButton {\n"
"    background-color:#f44336;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Green when pressed */\n"
"}")
        self.eraseButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/assets/delete-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraseButton.setIcon(icon8)
        self.eraseButton.setIconSize(QtCore.QSize(22, 22))
        self.eraseButton.setObjectName("eraseButton")
        self.gridLayout_7.addWidget(self.eraseButton, 1, 3, 1, 1)
        self.flashButton = QtWidgets.QPushButton(self.controller_page)
        self.flashButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashButton.setFont(font)
        self.flashButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flashButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashButton.setStyleSheet("QPushButton {\n"
"    background-color:#06768d;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #065465; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003747; /* Even Darker Green when pressed */\n"
"}")
        self.flashButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/assets/download-2-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flashButton.setIcon(icon9)
        self.flashButton.setIconSize(QtCore.QSize(22, 22))
        self.flashButton.setObjectName("flashButton")
        self.gridLayout_7.addWidget(self.flashButton, 1, 2, 1, 1)
        self.main_page.addWidget(self.controller_page)
        self.controller_data = QtWidgets.QWidget()
        self.controller_data.setObjectName("controller_data")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.controller_data)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.controller_data)
        self.frame_3.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.controller_finder_status = QtWidgets.QLabel(self.frame_3)
        self.controller_finder_status.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.controller_finder_status.setFont(font)
        self.controller_finder_status.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.controller_finder_status.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.controller_finder_status.setObjectName("controller_finder_status")
        self.horizontalLayout_3.addWidget(self.controller_finder_status)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.devicesDataView = QtWidgets.QTableView(self.frame_3)
        self.devicesDataView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesDataView.sizePolicy().hasHeightForWidth())
        self.devicesDataView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.devicesDataView.setFont(font)
        self.devicesDataView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.devicesDataView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.devicesDataView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.devicesDataView.setAlternatingRowColors(True)
        self.devicesDataView.setObjectName("devicesDataView")
        self.gridLayout_9.addWidget(self.devicesDataView, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_3, 3, 0, 1, 9)
        self.mcu_status = QtWidgets.QComboBox(self.controller_data)
        self.mcu_status.setMaximumSize(QtCore.QSize(100, 40))
        self.mcu_status.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mcu_status.setStyleSheet("QComboBox{    \n"
"    padding-left:10px;    \n"
"padding-right:10px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.mcu_status.setObjectName("mcu_status")
        self.mcu_status.addItem("")
        self.mcu_status.addItem("")
        self.mcu_status.addItem("")
        self.gridLayout_10.addWidget(self.mcu_status, 2, 6, 1, 1)
        self.time_frame = QtWidgets.QComboBox(self.controller_data)
        self.time_frame.setMaximumSize(QtCore.QSize(100, 40))
        self.time_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.time_frame.setStyleSheet("#time_frame{    \n"
"    padding-left:10px;    \n"
"padding-right:10px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"#time_frame::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"#time_frame::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"#time_frame:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"#time_frame QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#time_frame QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.time_frame.setObjectName("time_frame")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.gridLayout_10.addWidget(self.time_frame, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.controller_data)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 10)
        self.controller_finder = QtWidgets.QPushButton(self.controller_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controller_finder.sizePolicy().hasHeightForWidth())
        self.controller_finder.setSizePolicy(sizePolicy)
        self.controller_finder.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.controller_finder.setFont(font)
        self.controller_finder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.controller_finder.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.controller_finder.setStyleSheet("QPushButton {\n"
"    background-color:#06768d;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #065465; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003747; /* Even Darker Green when pressed */\n"
"}")
        self.controller_finder.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/assets/search-9-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controller_finder.setIcon(icon10)
        self.controller_finder.setIconSize(QtCore.QSize(25, 25))
        self.controller_finder.setObjectName("controller_finder")
        self.gridLayout_10.addWidget(self.controller_finder, 2, 8, 1, 1)
        self.device_id_input = QtWidgets.QLineEdit(self.controller_data)
        self.device_id_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.device_id_input.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.device_id_input.setMaxLength(16)
        self.device_id_input.setObjectName("device_id_input")
        self.gridLayout_10.addWidget(self.device_id_input, 2, 1, 1, 1)
        self.device_type = QtWidgets.QComboBox(self.controller_data)
        self.device_type.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.device_type.setFont(font)
        self.device_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.device_type.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.device_type.setStyleSheet("#device_type{\n"
"    padding-left:10px;    \n"
"padding-right:20px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"#device_type::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"#device_type::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"#device_type:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"#device_type QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#device_type QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.device_type.setObjectName("device_type")
        self.device_type.addItem("")
        self.device_type.addItem("")
        self.device_type.addItem("")
        self.gridLayout_10.addWidget(self.device_type, 2, 4, 1, 1)
        self.boxlot_finder = QtWidgets.QComboBox(self.controller_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxlot_finder.sizePolicy().hasHeightForWidth())
        self.boxlot_finder.setSizePolicy(sizePolicy)
        self.boxlot_finder.setMaximumSize(QtCore.QSize(150, 40))
        self.boxlot_finder.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.boxlot_finder.setObjectName("boxlot_finder")
        self.gridLayout_10.addWidget(self.boxlot_finder, 2, 7, 1, 1)
        self.main_page.addWidget(self.controller_data)
        self.inspection_config_page = QtWidgets.QWidget()
        self.inspection_config_page.setObjectName("inspection_config_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.inspection_config_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.inspection_config_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 2, 0, 1, 1)
        self.incomeTableView = QtWidgets.QTableView(self.frame_4)
        self.incomeTableView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeTableView.sizePolicy().hasHeightForWidth())
        self.incomeTableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.incomeTableView.setFont(font)
        self.incomeTableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.incomeTableView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.incomeTableView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.incomeTableView.setAlternatingRowColors(True)
        self.incomeTableView.setObjectName("incomeTableView")
        self.gridLayout_11.addWidget(self.incomeTableView, 1, 0, 1, 1)
        self.issue_list_table = QtWidgets.QTableView(self.frame_4)
        self.issue_list_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.issue_list_table.sizePolicy().hasHeightForWidth())
        self.issue_list_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.issue_list_table.setFont(font)
        self.issue_list_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.issue_list_table.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.issue_list_table.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.issue_list_table.setAlternatingRowColors(True)
        self.issue_list_table.setObjectName("issue_list_table")
        self.gridLayout_11.addWidget(self.issue_list_table, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.inspection_config_page)
        self.frame_5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_5.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 88, 381, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_18.setObjectName("label_18")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(20, 69, 211, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.label_30.setObjectName("label_30")
        self.error_type = QtWidgets.QComboBox(self.frame_5)
        self.error_type.setGeometry(QtCore.QRect(20, 597, 361, 40))
        self.error_type.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.error_type.setFont(font)
        self.error_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.error_type.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.error_type.setObjectName("error_type")
        self.error_type.addItem("")
        self.error_type.addItem("")
        self.error_type.addItem("")
        self.error_type.addItem("")
        self.issue_input = QtWidgets.QLineEdit(self.frame_5)
        self.issue_input.setGeometry(QtCore.QRect(20, 658, 361, 40))
        self.issue_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.issue_input.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.issue_input.setMaxLength(16)
        self.issue_input.setObjectName("issue_input")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(11, 560, 381, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_19.setObjectName("label_19")
        self.label_31 = QtWidgets.QLabel(self.frame_5)
        self.label_31.setGeometry(QtCore.QRect(21, 540, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.label_31.setObjectName("label_31")
        self.update_issue_bt = QtWidgets.QPushButton(self.frame_5)
        self.update_issue_bt.setGeometry(QtCore.QRect(20, 717, 361, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.update_issue_bt.setFont(font)
        self.update_issue_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_issue_bt.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.update_issue_bt.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.update_issue_bt.setCheckable(True)
        self.update_issue_bt.setChecked(False)
        self.update_issue_bt.setAutoRepeat(False)
        self.update_issue_bt.setObjectName("update_issue_bt")
        self.incom_date = QtWidgets.QLineEdit(self.frame_5)
        self.incom_date.setGeometry(QtCore.QRect(112, 120, 211, 40))
        self.incom_date.setMaximumSize(QtCore.QSize(16777215, 40))
        self.incom_date.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.incom_date.setMaxLength(13)
        self.incom_date.setObjectName("incom_date")
        self.income_qt = QtWidgets.QLineEdit(self.frame_5)
        self.income_qt.setGeometry(QtCore.QRect(112, 173, 211, 40))
        self.income_qt.setMaximumSize(QtCore.QSize(16777215, 40))
        self.income_qt.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.income_qt.setMaxLength(3)
        self.income_qt.setObjectName("income_qt")
        self.income_submit = QtWidgets.QPushButton(self.frame_5)
        self.income_submit.setGeometry(QtCore.QRect(20, 230, 361, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.income_submit.setFont(font)
        self.income_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.income_submit.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.income_submit.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.income_submit.setCheckable(True)
        self.income_submit.setChecked(False)
        self.income_submit.setAutoRepeat(False)
        self.income_submit.setObjectName("income_submit")
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setGeometry(QtCore.QRect(20, 125, 81, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:15pt;")
        self.label_32.setObjectName("label_32")
        self.label_37 = QtWidgets.QLabel(self.frame_5)
        self.label_37.setGeometry(QtCore.QRect(22, 178, 81, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:15pt;")
        self.label_37.setObjectName("label_37")
        self.insign_status = QtWidgets.QLabel(self.frame_5)
        self.insign_status.setGeometry(QtCore.QRect(20, 20, 361, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.insign_status.setFont(font)
        self.insign_status.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.insign_status.setText("")
        self.insign_status.setObjectName("insign_status")
        self.export_document_butt = QtWidgets.QPushButton(self.frame_5)
        self.export_document_butt.setGeometry(QtCore.QRect(19, 480, 361, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.export_document_butt.setFont(font)
        self.export_document_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_document_butt.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.export_document_butt.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.export_document_butt.setCheckable(True)
        self.export_document_butt.setChecked(False)
        self.export_document_butt.setAutoRepeat(False)
        self.export_document_butt.setObjectName("export_document_butt")
        self.alive_lot_box = QtWidgets.QComboBox(self.frame_5)
        self.alive_lot_box.setGeometry(QtCore.QRect(110, 390, 201, 40))
        self.alive_lot_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.alive_lot_box.setFont(font)
        self.alive_lot_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alive_lot_box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.alive_lot_box.setObjectName("alive_lot_box")
        self.label_21 = QtWidgets.QLabel(self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(10, 310, 381, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_21.setObjectName("label_21")
        self.label_34 = QtWidgets.QLabel(self.frame_5)
        self.label_34.setGeometry(QtCore.QRect(20, 290, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.frame_5)
        self.label_36.setGeometry(QtCore.QRect(30, 340, 81, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:15pt;")
        self.label_36.setObjectName("label_36")
        self.lot_finder = QtWidgets.QLineEdit(self.frame_5)
        self.lot_finder.setGeometry(QtCore.QRect(110, 340, 201, 40))
        self.lot_finder.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lot_finder.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.lot_finder.setMaxLength(13)
        self.lot_finder.setObjectName("lot_finder")
        self.show_done_lot = QtWidgets.QCheckBox(self.frame_5)
        self.show_done_lot.setGeometry(QtCore.QRect(110, 440, 181, 31))
        self.show_done_lot.setStyleSheet("color:white;")
        self.show_done_lot.setTristate(False)
        self.show_done_lot.setObjectName("show_done_lot")
        self.lot_finder_butto = QtWidgets.QPushButton(self.frame_5)
        self.lot_finder_butto.setGeometry(QtCore.QRect(320, 340, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lot_finder_butto.sizePolicy().hasHeightForWidth())
        self.lot_finder_butto.setSizePolicy(sizePolicy)
        self.lot_finder_butto.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lot_finder_butto.setFont(font)
        self.lot_finder_butto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lot_finder_butto.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lot_finder_butto.setStyleSheet("QPushButton {\n"
"    background-color:#06768d;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #065465; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003747; /* Even Darker Green when pressed */\n"
"}")
        self.lot_finder_butto.setText("")
        self.lot_finder_butto.setIcon(icon10)
        self.lot_finder_butto.setIconSize(QtCore.QSize(25, 25))
        self.lot_finder_butto.setObjectName("lot_finder_butto")
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 1, 1)
        self.main_page.addWidget(self.inspection_config_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.onStageView = QtWidgets.QTableView(self.frame_7)
        self.onStageView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onStageView.sizePolicy().hasHeightForWidth())
        self.onStageView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.onStageView.setFont(font)
        self.onStageView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.onStageView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.onStageView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.onStageView.setAlternatingRowColors(True)
        self.onStageView.setObjectName("onStageView")
        self.gridLayout_12.addWidget(self.onStageView, 4, 0, 1, 1)
        self.sensorRangeView_Old = QtWidgets.QTableView(self.frame_7)
        self.sensorRangeView_Old.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorRangeView_Old.sizePolicy().hasHeightForWidth())
        self.sensorRangeView_Old.setSizePolicy(sizePolicy)
        self.sensorRangeView_Old.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.sensorRangeView_Old.setFont(font)
        self.sensorRangeView_Old.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sensorRangeView_Old.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.sensorRangeView_Old.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.sensorRangeView_Old.setAlternatingRowColors(True)
        self.sensorRangeView_Old.setObjectName("sensorRangeView_Old")
        self.gridLayout_12.addWidget(self.sensorRangeView_Old, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_6.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(10, 88, 381, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_20.setObjectName("label_20")
        self.label_33 = QtWidgets.QLabel(self.frame_6)
        self.label_33.setGeometry(QtCore.QRect(20, 69, 221, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.label_33.setObjectName("label_33")
        self.air_submit_bt = QtWidgets.QPushButton(self.frame_6)
        self.air_submit_bt.setGeometry(QtCore.QRect(20, 230, 361, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.air_submit_bt.setFont(font)
        self.air_submit_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.air_submit_bt.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.air_submit_bt.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.air_submit_bt.setCheckable(True)
        self.air_submit_bt.setChecked(False)
        self.air_submit_bt.setAutoRepeat(False)
        self.air_submit_bt.setObjectName("air_submit_bt")
        self.label_35 = QtWidgets.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(20, 125, 81, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:15pt;")
        self.label_35.setObjectName("label_35")
        self.set_stage_boxlot_Box = QtWidgets.QComboBox(self.frame_6)
        self.set_stage_boxlot_Box.setGeometry(QtCore.QRect(20, 160, 361, 40))
        self.set_stage_boxlot_Box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.set_stage_boxlot_Box.setFont(font)
        self.set_stage_boxlot_Box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_stage_boxlot_Box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"    font-size:15pt;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.set_stage_boxlot_Box.setObjectName("set_stage_boxlot_Box")
        self.range_status = QtWidgets.QLabel(self.frame_6)
        self.range_status.setGeometry(QtCore.QRect(20, 20, 361, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.range_status.setFont(font)
        self.range_status.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.range_status.setText("")
        self.range_status.setObjectName("range_status")
        self.gridLayout_5.addWidget(self.frame_6, 0, 1, 1, 1)
        self.main_page.addWidget(self.page)
        self.gridLayout.addWidget(self.main_page, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_page.setCurrentIndex(0)
        self.mini_controller_btn.clicked['bool'].connect(self.big_controller_btn.setChecked) # type: ignore
        self.mini_menu_btn.toggled['bool'].connect(self.mini_menu.setVisible) # type: ignore
        self.mini_menu_btn.toggled['bool'].connect(self.big_menu.setHidden) # type: ignore
        self.mini_controller_btn.clicked['bool'].connect(self.big_controller_btn.setChecked) # type: ignore
        self.mini_db_btn.clicked['bool'].connect(self.big_db_btn.setChecked) # type: ignore
        self.big_menu_btn.toggled['bool'].connect(self.mini_menu.setVisible) # type: ignore
        self.big_menu_btn.toggled['bool'].connect(self.mini_menu.setVisible) # type: ignore
        self.big_menu_btn.toggled['bool'].connect(self.big_menu.setHidden) # type: ignore
        self.mini_menu_btn.clicked['bool'].connect(self.big_menu_btn.setChecked) # type: ignore
        self.big_menu_btn.clicked['bool'].connect(self.mini_menu_btn.setChecked) # type: ignore
        self.powerOffButton.toggled['bool'].connect(self.powerOnButton.setChecked) # type: ignore
        self.powerOnButton.toggled['bool'].connect(self.powerOffButton.setChecked) # type: ignore
        self.powerOffButton.toggled['bool'].connect(self.powerOnButton.setVisible) # type: ignore
        self.powerOffButton.toggled['bool'].connect(self.powerOffButton.setHidden) # type: ignore
        self.powerOnButton.toggled['bool'].connect(self.powerOffButton.setVisible) # type: ignore
        self.powerOnButton.toggled['bool'].connect(self.powerOnButton.setHidden) # type: ignore
        self.serial_r.clicked['bool'].connect(self.serial_s.setVisible) # type: ignore
        self.serial_r.clicked['bool'].connect(self.serial_r.setHidden) # type: ignore
        self.serial_s.clicked['bool'].connect(self.serial_s.setHidden) # type: ignore
        self.serial_s.clicked['bool'].connect(self.serial_r.setVisible) # type: ignore
        self.mini_controller_btn.clicked['bool'].connect(self.big_controller_btn.setChecked) # type: ignore
        self.mini_db_btn.clicked['bool'].connect(self.big_db_btn.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.big_menu_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/assets/SDE-Logo-Login_mini.png\"/></p></body></html>"))
        self.big_db_btn.setText(_translate("MainWindow", " Data Base"))
        self.big_insign_bt.setText(_translate("MainWindow", " Insign"))
        self.big_controller_btn.setText(_translate("MainWindow", " Controller"))
        self.flashStatusLabel.setText(_translate("MainWindow", "Status : None"))
        self.label_28.setText(_translate("MainWindow", "Serial Monitor"))
        self.ap_enable.setText(_translate("MainWindow", "Protection"))
        self.label_12.setText(_translate("MainWindow", "Serial Port"))
        self.label_13.setText(_translate("MainWindow", "Power"))
        self.label_2.setText(_translate("MainWindow", "___________________________________"))
        self.inspec_enable.setText(_translate("MainWindow", "Inspection Mode"))
        self.powerOnButton.setText(_translate("MainWindow", "On"))
        self.powerOffButton.setText(_translate("MainWindow", "Off"))
        self.label_3.setText(_translate("MainWindow", "Device Configuration"))
        self.label_14.setText(_translate("MainWindow", "___________________________________"))
        self.label_26.setText(_translate("MainWindow", "Device Monitor"))
        self.label_27.setText(_translate("MainWindow", "Serial Log"))
        self.serial_r.setText(_translate("MainWindow", "Read"))
        self.serial_s.setText(_translate("MainWindow", "Stop"))
        self.label_15.setText(_translate("MainWindow", "___________________________________"))
        self.label_29.setText(_translate("MainWindow", "Device Rejection"))
        self.RejectButton.setText(_translate("MainWindow", "Reject"))
        self.error_type_box.setItemText(0, _translate("MainWindow", "Device Type"))
        self.error_type_box.setItemText(1, _translate("MainWindow", "Actuator Controller"))
        self.error_type_box.setItemText(2, _translate("MainWindow", "Sensor Controller"))
        self.label.setText(_translate("MainWindow", "Controller Board : Erasing & Programming"))
        self.controller_finder_status.setText(_translate("MainWindow", "Status : None"))
        self.mcu_status.setItemText(0, _translate("MainWindow", "Status"))
        self.mcu_status.setItemText(1, _translate("MainWindow", "Good"))
        self.mcu_status.setItemText(2, _translate("MainWindow", "NG"))
        self.time_frame.setItemText(0, _translate("MainWindow", "Time"))
        self.time_frame.setItemText(1, _translate("MainWindow", "Hour"))
        self.time_frame.setItemText(2, _translate("MainWindow", "Day"))
        self.time_frame.setItemText(3, _translate("MainWindow", "Week"))
        self.time_frame.setItemText(4, _translate("MainWindow", "Month"))
        self.time_frame.setItemText(5, _translate("MainWindow", "Year"))
        self.label_4.setText(_translate("MainWindow", "Controller Board Data"))
        self.device_id_input.setPlaceholderText(_translate("MainWindow", "Device ID"))
        self.device_type.setItemText(0, _translate("MainWindow", "Device Type"))
        self.device_type.setItemText(1, _translate("MainWindow", "Actuator Controller"))
        self.device_type.setItemText(2, _translate("MainWindow", "Sensor Controller"))
        self.label_6.setText(_translate("MainWindow", "Incoming Lot"))
        self.label_7.setText(_translate("MainWindow", " Issue List"))
        self.label_18.setText(_translate("MainWindow", "______________________________________________________________________"))
        self.label_30.setText(_translate("MainWindow", "Incoming Devices"))
        self.error_type.setItemText(0, _translate("MainWindow", "Device Type"))
        self.error_type.setItemText(1, _translate("MainWindow", "All"))
        self.error_type.setItemText(2, _translate("MainWindow", "Actuator Controller"))
        self.error_type.setItemText(3, _translate("MainWindow", "Sensor Controller"))
        self.issue_input.setPlaceholderText(_translate("MainWindow", "Issue"))
        self.label_19.setText(_translate("MainWindow", "______________________________________________________________________"))
        self.label_31.setText(_translate("MainWindow", "Issue Update"))
        self.update_issue_bt.setText(_translate("MainWindow", "Update"))
        self.incom_date.setPlaceholderText(_translate("MainWindow", "L-20XXXXXX-XX"))
        self.income_qt.setPlaceholderText(_translate("MainWindow", "Quantity (pcs)"))
        self.income_submit.setText(_translate("MainWindow", "Submit"))
        self.label_32.setText(_translate("MainWindow", "Lot No."))
        self.label_37.setText(_translate("MainWindow", "Quantity"))
        self.export_document_butt.setText(_translate("MainWindow", "Export"))
        self.label_21.setText(_translate("MainWindow", "______________________________________________________________________"))
        self.label_34.setText(_translate("MainWindow", "Export Result"))
        self.label_36.setText(_translate("MainWindow", "Lot No."))
        self.lot_finder.setPlaceholderText(_translate("MainWindow", "L-20XXXXXX-XX"))
        self.show_done_lot.setText(_translate("MainWindow", "Available Lot"))
        self.label_8.setText(_translate("MainWindow", "Air Quality Range"))
        self.label_9.setText(_translate("MainWindow", "Air Quality on Stage"))
        self.label_20.setText(_translate("MainWindow", "______________________________________________________________________"))
        self.label_33.setText(_translate("MainWindow", "Air Quality Set Stage"))
        self.air_submit_bt.setText(_translate("MainWindow", "Submit"))
        self.label_35.setText(_translate("MainWindow", "Lot No."))
import sde_rc
