# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\es-sde-now.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1370, 853)
        MainWindow.setMinimumSize(QtCore.QSize(1370, 704))
        MainWindow.setStyleSheet("    font-family: SCG;\n"
"    font-size:15pt;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_page = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_page.setEnabled(True)
        self.main_page.setMinimumSize(QtCore.QSize(1000, 20))
        self.main_page.setTabletTracking(False)
        self.main_page.setAcceptDrops(False)
        self.main_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_page.setAutoFillBackground(False)
        self.main_page.setObjectName("main_page")
        self.controller_page = QtWidgets.QWidget()
        self.controller_page.setObjectName("controller_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.controller_page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.controller_page)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 5)
        self.programFileComboBox = QtWidgets.QComboBox(self.controller_page)
        self.programFileComboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.programFileComboBox.setFont(font)
        self.programFileComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.programFileComboBox.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.programFileComboBox.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.programFileComboBox.setObjectName("programFileComboBox")
        self.gridLayout_7.addWidget(self.programFileComboBox, 1, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.controller_page)
        self.label_5.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:black;\n"
"text-align:center;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.controller_page)
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.uart_portBox = QtWidgets.QComboBox(self.frame)
        self.uart_portBox.setGeometry(QtCore.QRect(10, 250, 201, 31))
        self.uart_portBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.uart_portBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uart_portBox.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    /*image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);*/\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.uart_portBox.setObjectName("uart_portBox")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 91, 52))
        self.label_12.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.label_13.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:white;")
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 191, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_2.setObjectName("label_2")
        self.powerOnButton = QtWidgets.QPushButton(self.frame)
        self.powerOnButton.setGeometry(QtCore.QRect(100, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.powerOnButton.setFont(font)
        self.powerOnButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerOnButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.powerOnButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.powerOnButton.setCheckable(True)
        self.powerOnButton.setChecked(False)
        self.powerOnButton.setAutoRepeat(False)
        self.powerOnButton.setObjectName("powerOnButton")
        self.powerOffButton = QtWidgets.QPushButton(self.frame)
        self.powerOffButton.setGeometry(QtCore.QRect(100, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.powerOffButton.setFont(font)
        self.powerOffButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerOffButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.powerOffButton.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.powerOffButton.setCheckable(True)
        self.powerOffButton.setChecked(False)
        self.powerOffButton.setAutoRepeat(False)
        self.powerOffButton.setAutoExclusive(False)
        self.powerOffButton.setObjectName("powerOffButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_3.setObjectName("label_3")
        self.boxlot_Box = QtWidgets.QComboBox(self.frame)
        self.boxlot_Box.setGeometry(QtCore.QRect(10, 160, 201, 31))
        self.boxlot_Box.setMaximumSize(QtCore.QSize(16777215, 40))
        self.boxlot_Box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boxlot_Box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"    font-size:12pt;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    /*image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);*/\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.boxlot_Box.setObjectName("boxlot_Box")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 131, 52))
        self.label_14.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:white;")
        self.label_14.setObjectName("label_14")
        self.finish_test = QtWidgets.QPushButton(self.frame)
        self.finish_test.setGeometry(QtCore.QRect(20, 510, 181, 41))
        self.finish_test.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.finish_test.setFont(font)
        self.finish_test.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finish_test.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.finish_test.setWhatsThis("")
        self.finish_test.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.finish_test.setIconSize(QtCore.QSize(35, 35))
        self.finish_test.setAutoRepeatInterval(101)
        self.finish_test.setObjectName("finish_test")
        self.clearListButton = QtWidgets.QPushButton(self.frame)
        self.clearListButton.setGeometry(QtCore.QRect(20, 370, 181, 41))
        self.clearListButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clearListButton.setFont(font)
        self.clearListButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearListButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.clearListButton.setWhatsThis("")
        self.clearListButton.setStyleSheet("QPushButton {\n"
"    background-color: #0077dd; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ac1dd; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2eb3ca; /* Even Darker Green when pressed */\n"
"}")
        self.clearListButton.setIconSize(QtCore.QSize(35, 35))
        self.clearListButton.setAutoRepeatInterval(101)
        self.clearListButton.setObjectName("clearListButton")
        self.flashButton = QtWidgets.QPushButton(self.frame)
        self.flashButton.setGeometry(QtCore.QRect(20, 310, 181, 41))
        self.flashButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashButton.setFont(font)
        self.flashButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flashButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.flashButton.setIconSize(QtCore.QSize(22, 22))
        self.flashButton.setObjectName("flashButton")
        self.label_14.raise_()
        self.powerOnButton.raise_()
        self.label_2.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.powerOffButton.raise_()
        self.label_3.raise_()
        self.uart_portBox.raise_()
        self.boxlot_Box.raise_()
        self.finish_test.raise_()
        self.clearListButton.raise_()
        self.flashButton.raise_()
        self.gridLayout_7.addWidget(self.frame, 1, 4, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.controller_page)
        self.frame_2.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.devicesTableView = QtWidgets.QTableView(self.frame_2)
        self.devicesTableView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesTableView.sizePolicy().hasHeightForWidth())
        self.devicesTableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.devicesTableView.setFont(font)
        self.devicesTableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.devicesTableView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.devicesTableView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.devicesTableView.setAlternatingRowColors(True)
        self.devicesTableView.setObjectName("devicesTableView")
        self.gridLayout_6.addWidget(self.devicesTableView, 3, 0, 1, 1)
        self.incomeTableView_2 = QtWidgets.QTableView(self.frame_2)
        self.incomeTableView_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeTableView_2.sizePolicy().hasHeightForWidth())
        self.incomeTableView_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.incomeTableView_2.setFont(font)
        self.incomeTableView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.incomeTableView_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.incomeTableView_2.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.incomeTableView_2.setAlternatingRowColors(True)
        self.incomeTableView_2.setObjectName("incomeTableView_2")
        self.gridLayout_6.addWidget(self.incomeTableView_2, 7, 0, 1, 1)
        self.sensorRangeView = QtWidgets.QTableView(self.frame_2)
        self.sensorRangeView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorRangeView.sizePolicy().hasHeightForWidth())
        self.sensorRangeView.setSizePolicy(sizePolicy)
        self.sensorRangeView.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.sensorRangeView.setFont(font)
        self.sensorRangeView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sensorRangeView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.sensorRangeView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.sensorRangeView.setAlternatingRowColors(True)
        self.sensorRangeView.setObjectName("sensorRangeView")
        self.gridLayout_6.addWidget(self.sensorRangeView, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flashStatusLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashStatusLabel.setFont(font)
        self.flashStatusLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel.setObjectName("flashStatusLabel")
        self.horizontalLayout.addWidget(self.flashStatusLabel)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.flashStatusLabel_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashStatusLabel_2.setFont(font)
        self.flashStatusLabel_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel_2.setObjectName("flashStatusLabel_2")
        self.gridLayout_6.addWidget(self.flashStatusLabel_2, 2, 0, 1, 1)
        self.flashStatusLabel_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashStatusLabel_3.setFont(font)
        self.flashStatusLabel_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel_3.setObjectName("flashStatusLabel_3")
        self.gridLayout_6.addWidget(self.flashStatusLabel_3, 5, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 2, 0, 1, 4)
        self.main_page.addWidget(self.controller_page)
        self.controller_data = QtWidgets.QWidget()
        self.controller_data.setObjectName("controller_data")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.controller_data)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.controller_data)
        self.frame_3.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.controller_finder_status = QtWidgets.QLabel(self.frame_3)
        self.controller_finder_status.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.controller_finder_status.setFont(font)
        self.controller_finder_status.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.controller_finder_status.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.controller_finder_status.setObjectName("controller_finder_status")
        self.horizontalLayout_3.addWidget(self.controller_finder_status)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.devicesDataView = QtWidgets.QTableView(self.frame_3)
        self.devicesDataView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesDataView.sizePolicy().hasHeightForWidth())
        self.devicesDataView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.devicesDataView.setFont(font)
        self.devicesDataView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.devicesDataView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.devicesDataView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.devicesDataView.setAlternatingRowColors(True)
        self.devicesDataView.setObjectName("devicesDataView")
        self.gridLayout_9.addWidget(self.devicesDataView, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_3, 3, 0, 1, 9)
        self.mcu_status = QtWidgets.QComboBox(self.controller_data)
        self.mcu_status.setMaximumSize(QtCore.QSize(100, 40))
        self.mcu_status.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mcu_status.setStyleSheet("QComboBox{    \n"
"    padding-left:10px;    \n"
"padding-right:10px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.mcu_status.setObjectName("mcu_status")
        self.mcu_status.addItem("")
        self.mcu_status.addItem("")
        self.mcu_status.addItem("")
        self.gridLayout_10.addWidget(self.mcu_status, 2, 6, 1, 1)
        self.time_frame = QtWidgets.QComboBox(self.controller_data)
        self.time_frame.setMaximumSize(QtCore.QSize(100, 40))
        self.time_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.time_frame.setStyleSheet("#time_frame{    \n"
"    padding-left:10px;    \n"
"padding-right:10px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"#time_frame::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"#time_frame::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"#time_frame:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"#time_frame QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#time_frame QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.time_frame.setObjectName("time_frame")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.time_frame.addItem("")
        self.gridLayout_10.addWidget(self.time_frame, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.controller_data)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 10)
        self.controller_finder = QtWidgets.QPushButton(self.controller_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controller_finder.sizePolicy().hasHeightForWidth())
        self.controller_finder.setSizePolicy(sizePolicy)
        self.controller_finder.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.controller_finder.setFont(font)
        self.controller_finder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.controller_finder.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.controller_finder.setStyleSheet("QPushButton {\n"
"    background-color:#06768d;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #065465; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003747; /* Even Darker Green when pressed */\n"
"}")
        self.controller_finder.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/assets/search-9-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controller_finder.setIcon(icon)
        self.controller_finder.setIconSize(QtCore.QSize(25, 25))
        self.controller_finder.setObjectName("controller_finder")
        self.gridLayout_10.addWidget(self.controller_finder, 2, 8, 1, 1)
        self.device_id_input = QtWidgets.QLineEdit(self.controller_data)
        self.device_id_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.device_id_input.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.device_id_input.setMaxLength(16)
        self.device_id_input.setObjectName("device_id_input")
        self.gridLayout_10.addWidget(self.device_id_input, 2, 1, 1, 1)
        self.device_type = QtWidgets.QComboBox(self.controller_data)
        self.device_type.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.device_type.setFont(font)
        self.device_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.device_type.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.device_type.setStyleSheet("#device_type{\n"
"    padding-left:10px;    \n"
"padding-right:20px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"#device_type::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"#device_type::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"#device_type:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"#device_type QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#device_type QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.device_type.setObjectName("device_type")
        self.device_type.addItem("")
        self.device_type.addItem("")
        self.device_type.addItem("")
        self.gridLayout_10.addWidget(self.device_type, 2, 4, 1, 1)
        self.boxlot_finder = QtWidgets.QComboBox(self.controller_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxlot_finder.sizePolicy().hasHeightForWidth())
        self.boxlot_finder.setSizePolicy(sizePolicy)
        self.boxlot_finder.setMaximumSize(QtCore.QSize(150, 40))
        self.boxlot_finder.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.boxlot_finder.setObjectName("boxlot_finder")
        self.gridLayout_10.addWidget(self.boxlot_finder, 2, 7, 1, 1)
        self.main_page.addWidget(self.controller_data)
        self.inspection_config_page = QtWidgets.QWidget()
        self.inspection_config_page.setObjectName("inspection_config_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.inspection_config_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.inspection_config_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.incomeTableView = QtWidgets.QTableView(self.frame_4)
        self.incomeTableView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeTableView.sizePolicy().hasHeightForWidth())
        self.incomeTableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.incomeTableView.setFont(font)
        self.incomeTableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.incomeTableView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.incomeTableView.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.incomeTableView.setAlternatingRowColors(True)
        self.incomeTableView.setObjectName("incomeTableView")
        self.gridLayout_11.addWidget(self.incomeTableView, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.inspection_config_page)
        self.frame_5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_5.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 88, 381, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_18.setObjectName("label_18")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(20, 60, 211, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.label_30.setObjectName("label_30")
        self.incom_date = QtWidgets.QLineEdit(self.frame_5)
        self.incom_date.setGeometry(QtCore.QRect(112, 120, 211, 40))
        self.incom_date.setMaximumSize(QtCore.QSize(16777215, 40))
        self.incom_date.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.incom_date.setMaxLength(13)
        self.incom_date.setObjectName("incom_date")
        self.income_submit = QtWidgets.QPushButton(self.frame_5)
        self.income_submit.setGeometry(QtCore.QRect(20, 190, 361, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.income_submit.setFont(font)
        self.income_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.income_submit.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.income_submit.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.income_submit.setCheckable(True)
        self.income_submit.setChecked(False)
        self.income_submit.setAutoRepeat(False)
        self.income_submit.setObjectName("income_submit")
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setGeometry(QtCore.QRect(20, 125, 81, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:15pt;")
        self.label_32.setObjectName("label_32")
        self.insign_status = QtWidgets.QLabel(self.frame_5)
        self.insign_status.setGeometry(QtCore.QRect(20, 20, 361, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.insign_status.setFont(font)
        self.insign_status.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.insign_status.setText("")
        self.insign_status.setObjectName("insign_status")
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 1, 1)
        self.main_page.addWidget(self.inspection_config_page)
        self.export_data = QtWidgets.QWidget()
        self.export_data.setObjectName("export_data")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.export_data)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.main_page_2 = QtWidgets.QStackedWidget(self.export_data)
        self.main_page_2.setEnabled(True)
        self.main_page_2.setMinimumSize(QtCore.QSize(1000, 20))
        self.main_page_2.setTabletTracking(False)
        self.main_page_2.setAcceptDrops(False)
        self.main_page_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_page_2.setAutoFillBackground(False)
        self.main_page_2.setObjectName("main_page_2")
        self.controller_page_2 = QtWidgets.QWidget()
        self.controller_page_2.setObjectName("controller_page_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.controller_page_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.controller_page_2)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 5)
        self.programFileComboBox_2 = QtWidgets.QComboBox(self.controller_page_2)
        self.programFileComboBox_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.programFileComboBox_2.setFont(font)
        self.programFileComboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.programFileComboBox_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.programFileComboBox_2.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.programFileComboBox_2.setObjectName("programFileComboBox_2")
        self.gridLayout_8.addWidget(self.programFileComboBox_2, 1, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.controller_page_2)
        self.label_8.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:black;\n"
"text-align:center;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.controller_page_2)
        self.frame_6.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_6.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.uart_portBox_2 = QtWidgets.QComboBox(self.frame_6)
        self.uart_portBox_2.setGeometry(QtCore.QRect(10, 250, 201, 31))
        self.uart_portBox_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.uart_portBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uart_portBox_2.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    /*image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);*/\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.uart_portBox_2.setObjectName("uart_portBox_2")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        self.label_15.setGeometry(QtCore.QRect(10, 200, 91, 52))
        self.label_15.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:white;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.label_16.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:white;")
        self.label_16.setObjectName("label_16")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 191, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_9.setObjectName("label_9")
        self.powerOnButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.powerOnButton_2.setGeometry(QtCore.QRect(100, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.powerOnButton_2.setFont(font)
        self.powerOnButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerOnButton_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.powerOnButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.powerOnButton_2.setCheckable(True)
        self.powerOnButton_2.setChecked(False)
        self.powerOnButton_2.setAutoRepeat(False)
        self.powerOnButton_2.setObjectName("powerOnButton_2")
        self.powerOffButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.powerOffButton_2.setGeometry(QtCore.QRect(100, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.powerOffButton_2.setFont(font)
        self.powerOffButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerOffButton_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.powerOffButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.powerOffButton_2.setCheckable(True)
        self.powerOffButton_2.setChecked(False)
        self.powerOffButton_2.setAutoRepeat(False)
        self.powerOffButton_2.setAutoExclusive(False)
        self.powerOffButton_2.setObjectName("powerOffButton_2")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_10.setObjectName("label_10")
        self.boxlot_Box_2 = QtWidgets.QComboBox(self.frame_6)
        self.boxlot_Box_2.setGeometry(QtCore.QRect(10, 160, 201, 31))
        self.boxlot_Box_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.boxlot_Box_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boxlot_Box_2.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:5px;\n"
"    font-size:12pt;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    /*image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);*/\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.boxlot_Box_2.setObjectName("boxlot_Box_2")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 131, 52))
        self.label_17.setMaximumSize(QtCore.QSize(16777210, 16777210))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:white;")
        self.label_17.setObjectName("label_17")
        self.finish_test_2 = QtWidgets.QPushButton(self.frame_6)
        self.finish_test_2.setGeometry(QtCore.QRect(20, 510, 181, 41))
        self.finish_test_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.finish_test_2.setFont(font)
        self.finish_test_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finish_test_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.finish_test_2.setWhatsThis("")
        self.finish_test_2.setStyleSheet("QPushButton {\n"
"    background-color: #f44336; /* Red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f; /* Darker Red */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}")
        self.finish_test_2.setIconSize(QtCore.QSize(35, 35))
        self.finish_test_2.setAutoRepeatInterval(101)
        self.finish_test_2.setObjectName("finish_test_2")
        self.clearListButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.clearListButton_2.setGeometry(QtCore.QRect(20, 370, 181, 41))
        self.clearListButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clearListButton_2.setFont(font)
        self.clearListButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearListButton_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.clearListButton_2.setWhatsThis("")
        self.clearListButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #02d2f5; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ac1dd; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2eb3ca; /* Even Darker Green when pressed */\n"
"}")
        self.clearListButton_2.setIconSize(QtCore.QSize(35, 35))
        self.clearListButton_2.setAutoRepeatInterval(101)
        self.clearListButton_2.setObjectName("clearListButton_2")
        self.flashButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.flashButton_2.setGeometry(QtCore.QRect(20, 310, 181, 41))
        self.flashButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashButton_2.setFont(font)
        self.flashButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flashButton_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.flashButton_2.setIconSize(QtCore.QSize(22, 22))
        self.flashButton_2.setObjectName("flashButton_2")
        self.gridLayout_8.addWidget(self.frame_6, 1, 4, 2, 1)
        self.frame_7 = QtWidgets.QFrame(self.controller_page_2)
        self.frame_7.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.devicesTableView_2 = QtWidgets.QTableView(self.frame_7)
        self.devicesTableView_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesTableView_2.sizePolicy().hasHeightForWidth())
        self.devicesTableView_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.devicesTableView_2.setFont(font)
        self.devicesTableView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.devicesTableView_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.devicesTableView_2.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.devicesTableView_2.setAlternatingRowColors(True)
        self.devicesTableView_2.setObjectName("devicesTableView_2")
        self.gridLayout_12.addWidget(self.devicesTableView_2, 3, 0, 1, 1)
        self.incomeTableView_3 = QtWidgets.QTableView(self.frame_7)
        self.incomeTableView_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeTableView_3.sizePolicy().hasHeightForWidth())
        self.incomeTableView_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.incomeTableView_3.setFont(font)
        self.incomeTableView_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.incomeTableView_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.incomeTableView_3.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.incomeTableView_3.setAlternatingRowColors(True)
        self.incomeTableView_3.setObjectName("incomeTableView_3")
        self.gridLayout_12.addWidget(self.incomeTableView_3, 7, 0, 1, 1)
        self.sensorRangeView_2 = QtWidgets.QTableView(self.frame_7)
        self.sensorRangeView_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorRangeView_2.sizePolicy().hasHeightForWidth())
        self.sensorRangeView_2.setSizePolicy(sizePolicy)
        self.sensorRangeView_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.sensorRangeView_2.setFont(font)
        self.sensorRangeView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sensorRangeView_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.sensorRangeView_2.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.sensorRangeView_2.setAlternatingRowColors(True)
        self.sensorRangeView_2.setObjectName("sensorRangeView_2")
        self.gridLayout_12.addWidget(self.sensorRangeView_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.flashStatusLabel_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashStatusLabel_4.setFont(font)
        self.flashStatusLabel_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel_4.setObjectName("flashStatusLabel_4")
        self.horizontalLayout_2.addWidget(self.flashStatusLabel_4)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.flashStatusLabel_5 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashStatusLabel_5.setFont(font)
        self.flashStatusLabel_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel_5.setObjectName("flashStatusLabel_5")
        self.gridLayout_12.addWidget(self.flashStatusLabel_5, 2, 0, 1, 1)
        self.flashStatusLabel_6 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.flashStatusLabel_6.setFont(font)
        self.flashStatusLabel_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flashStatusLabel_6.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.flashStatusLabel_6.setObjectName("flashStatusLabel_6")
        self.gridLayout_12.addWidget(self.flashStatusLabel_6, 5, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_7, 2, 0, 1, 4)
        self.main_page_2.addWidget(self.controller_page_2)
        self.controller_data_2 = QtWidgets.QWidget()
        self.controller_data_2.setObjectName("controller_data_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.controller_data_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_8 = QtWidgets.QFrame(self.controller_data_2)
        self.frame_8.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.controller_finder_status_2 = QtWidgets.QLabel(self.frame_8)
        self.controller_finder_status_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.controller_finder_status_2.setFont(font)
        self.controller_finder_status_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.controller_finder_status_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.controller_finder_status_2.setObjectName("controller_finder_status_2")
        self.horizontalLayout_4.addWidget(self.controller_finder_status_2)
        self.gridLayout_14.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.devicesDataView_2 = QtWidgets.QTableView(self.frame_8)
        self.devicesDataView_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesDataView_2.sizePolicy().hasHeightForWidth())
        self.devicesDataView_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.devicesDataView_2.setFont(font)
        self.devicesDataView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.devicesDataView_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.devicesDataView_2.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.devicesDataView_2.setAlternatingRowColors(True)
        self.devicesDataView_2.setObjectName("devicesDataView_2")
        self.gridLayout_14.addWidget(self.devicesDataView_2, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_8, 3, 0, 1, 9)
        self.mcu_status_2 = QtWidgets.QComboBox(self.controller_data_2)
        self.mcu_status_2.setMaximumSize(QtCore.QSize(100, 40))
        self.mcu_status_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mcu_status_2.setStyleSheet("QComboBox{    \n"
"    padding-left:10px;    \n"
"padding-right:10px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.mcu_status_2.setObjectName("mcu_status_2")
        self.mcu_status_2.addItem("")
        self.mcu_status_2.addItem("")
        self.mcu_status_2.addItem("")
        self.gridLayout_13.addWidget(self.mcu_status_2, 2, 6, 1, 1)
        self.time_frame_2 = QtWidgets.QComboBox(self.controller_data_2)
        self.time_frame_2.setMaximumSize(QtCore.QSize(100, 40))
        self.time_frame_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.time_frame_2.setStyleSheet("#time_frame{    \n"
"    padding-left:10px;    \n"
"padding-right:10px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"#time_frame::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"#time_frame::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"#time_frame:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"#time_frame QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#time_frame QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.time_frame_2.setObjectName("time_frame_2")
        self.time_frame_2.addItem("")
        self.time_frame_2.addItem("")
        self.time_frame_2.addItem("")
        self.time_frame_2.addItem("")
        self.time_frame_2.addItem("")
        self.time_frame_2.addItem("")
        self.gridLayout_13.addWidget(self.time_frame_2, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.controller_data_2)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 10)
        self.controller_finder_2 = QtWidgets.QPushButton(self.controller_data_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controller_finder_2.sizePolicy().hasHeightForWidth())
        self.controller_finder_2.setSizePolicy(sizePolicy)
        self.controller_finder_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.controller_finder_2.setFont(font)
        self.controller_finder_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.controller_finder_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.controller_finder_2.setStyleSheet("QPushButton {\n"
"    background-color:#06768d;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #065465; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003747; /* Even Darker Green when pressed */\n"
"}")
        self.controller_finder_2.setText("")
        self.controller_finder_2.setIcon(icon)
        self.controller_finder_2.setIconSize(QtCore.QSize(25, 25))
        self.controller_finder_2.setObjectName("controller_finder_2")
        self.gridLayout_13.addWidget(self.controller_finder_2, 2, 8, 1, 1)
        self.device_id_input_2 = QtWidgets.QLineEdit(self.controller_data_2)
        self.device_id_input_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.device_id_input_2.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.device_id_input_2.setMaxLength(16)
        self.device_id_input_2.setObjectName("device_id_input_2")
        self.gridLayout_13.addWidget(self.device_id_input_2, 2, 1, 1, 1)
        self.device_type_2 = QtWidgets.QComboBox(self.controller_data_2)
        self.device_type_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.device_type_2.setFont(font)
        self.device_type_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.device_type_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.device_type_2.setStyleSheet("#device_type{\n"
"    padding-left:10px;    \n"
"padding-right:20px;\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"}\n"
"#device_type::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"#device_type::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"#device_type:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"#device_type QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#device_type QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.device_type_2.setObjectName("device_type_2")
        self.device_type_2.addItem("")
        self.device_type_2.addItem("")
        self.device_type_2.addItem("")
        self.gridLayout_13.addWidget(self.device_type_2, 2, 4, 1, 1)
        self.boxlot_finder_2 = QtWidgets.QComboBox(self.controller_data_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxlot_finder_2.sizePolicy().hasHeightForWidth())
        self.boxlot_finder_2.setSizePolicy(sizePolicy)
        self.boxlot_finder_2.setMaximumSize(QtCore.QSize(150, 40))
        self.boxlot_finder_2.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.boxlot_finder_2.setObjectName("boxlot_finder_2")
        self.gridLayout_13.addWidget(self.boxlot_finder_2, 2, 7, 1, 1)
        self.main_page_2.addWidget(self.controller_data_2)
        self.inspection_config_page_2 = QtWidgets.QWidget()
        self.inspection_config_page_2.setObjectName("inspection_config_page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.inspection_config_page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.inspection_config_page_2)
        self.frame_10.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_10.setStyleSheet("background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 0px 0px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.insign_status_2 = QtWidgets.QLabel(self.frame_10)
        self.insign_status_2.setGeometry(QtCore.QRect(20, 20, 361, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.insign_status_2.setFont(font)
        self.insign_status_2.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.insign_status_2.setText("")
        self.insign_status_2.setObjectName("insign_status_2")
        self.export_document_butt = QtWidgets.QPushButton(self.frame_10)
        self.export_document_butt.setGeometry(QtCore.QRect(19, 270, 361, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.export_document_butt.setFont(font)
        self.export_document_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_document_butt.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.export_document_butt.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker Green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #357a38; /* Even Darker Green when pressed */\n"
"}")
        self.export_document_butt.setCheckable(True)
        self.export_document_butt.setChecked(False)
        self.export_document_butt.setAutoRepeat(False)
        self.export_document_butt.setObjectName("export_document_butt")
        self.alive_lot_box = QtWidgets.QComboBox(self.frame_10)
        self.alive_lot_box.setGeometry(QtCore.QRect(110, 200, 201, 40))
        self.alive_lot_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.alive_lot_box.setFont(font)
        self.alive_lot_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alive_lot_box.setStyleSheet("QComboBox{    \n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"    border:1px solid black;\n"
"    padding-left:10px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border:0px\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/newPrefix/assets/arrow-down-sign-to-navigate.png);\n"
"    width:15px;    \n"
"    heigth:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    background-color:#fff;\n"
"    outline:0px;\n"
"}\n"
"")
        self.alive_lot_box.setObjectName("alive_lot_box")
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        self.label_22.setGeometry(QtCore.QRect(10, 90, 381, 20))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:white;\n"
"    text-align:center;")
        self.label_22.setObjectName("label_22")
        self.label_35 = QtWidgets.QLabel(self.frame_10)
        self.label_35.setGeometry(QtCore.QRect(20, 70, 186, 32))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.frame_10)
        self.label_37.setGeometry(QtCore.QRect(30, 140, 81, 41))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:15pt;")
        self.label_37.setObjectName("label_37")
        self.lot_finder = QtWidgets.QLineEdit(self.frame_10)
        self.lot_finder.setGeometry(QtCore.QRect(110, 140, 201, 40))
        self.lot_finder.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lot_finder.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius: 5px;\n"
"  border:1px solid black;\n"
"  padding: 5px 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border:4px solid #c2dbfe;\n"
"}\n"
"")
        self.lot_finder.setMaxLength(13)
        self.lot_finder.setObjectName("lot_finder")
        self.lot_finder_butto = QtWidgets.QPushButton(self.frame_10)
        self.lot_finder_butto.setGeometry(QtCore.QRect(320, 140, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lot_finder_butto.sizePolicy().hasHeightForWidth())
        self.lot_finder_butto.setSizePolicy(sizePolicy)
        self.lot_finder_butto.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lot_finder_butto.setFont(font)
        self.lot_finder_butto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lot_finder_butto.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lot_finder_butto.setStyleSheet("QPushButton {\n"
"    background-color:#06768d;\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #065465; /* Darker Green */\n"
"box-shadow: 10px 10px 5px rgba(182, 191, 193, 0.5);\n"
"    border:1px solid #808080;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003747; /* Even Darker Green when pressed */\n"
"}")
        self.lot_finder_butto.setText("")
        self.lot_finder_butto.setIcon(icon)
        self.lot_finder_butto.setIconSize(QtCore.QSize(25, 25))
        self.lot_finder_butto.setObjectName("lot_finder_butto")
        self.gridLayout_4.addWidget(self.frame_10, 0, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.inspection_config_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("background-color:#d9dadb;\n"
"border-radius: 10px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:white;\n"
"background-color:#222222;\n"
"border-radius: 10px;\n"
"padding: 10px 10px;\n"
"margin-right:0px")
        self.label_19.setObjectName("label_19")
        self.gridLayout_15.addWidget(self.label_19, 0, 0, 1, 1)
        self.incomeTableView_4 = QtWidgets.QTableView(self.frame_9)
        self.incomeTableView_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeTableView_4.sizePolicy().hasHeightForWidth())
        self.incomeTableView_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        self.incomeTableView_4.setFont(font)
        self.incomeTableView_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.incomeTableView_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.incomeTableView_4.setStyleSheet("    border:1px solid #1c305c;\n"
"background-color:white;\n"
"    border-radius: 0px;\n"
"    padding: 0px 0px;")
        self.incomeTableView_4.setAlternatingRowColors(True)
        self.incomeTableView_4.setObjectName("incomeTableView_4")
        self.gridLayout_15.addWidget(self.incomeTableView_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_9, 0, 0, 1, 1)
        self.main_page_2.addWidget(self.inspection_config_page_2)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.main_page_2.addWidget(self.page_2)
        self.gridLayout_16.addWidget(self.main_page_2, 0, 0, 2, 2)
        self.insign_status_3 = QtWidgets.QLabel(self.export_data)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(18)
        self.insign_status_3.setFont(font)
        self.insign_status_3.setStyleSheet("color:white;\n"
"    text-align:center;\n"
"    font-size:18pt;")
        self.insign_status_3.setText("")
        self.insign_status_3.setObjectName("insign_status_3")
        self.gridLayout_16.addWidget(self.insign_status_3, 1, 1, 1, 1)
        self.main_page.addWidget(self.export_data)
        self.gridLayout.addWidget(self.main_page, 0, 1, 1, 1)
        self.big_menu = QtWidgets.QFrame(self.centralwidget)
        self.big_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.big_menu.setStyleSheet("background-color:    #222222;\n"
"border-radius: 0px;\n"
"padding: 0px 0px;")
        self.big_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.big_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.big_menu.setObjectName("big_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.big_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.big_menu_btn = QtWidgets.QPushButton(self.big_menu)
        self.big_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_menu_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/assets/SDE-Logo-Login_mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_menu_btn.setIcon(icon1)
        self.big_menu_btn.setIconSize(QtCore.QSize(150, 150))
        self.big_menu_btn.setCheckable(True)
        self.big_menu_btn.setObjectName("big_menu_btn")
        self.gridLayout_3.addWidget(self.big_menu_btn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 7, 1, 1, 1)
        self.big_db_btn = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_db_btn.setFont(font)
        self.big_db_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_db_btn.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/assets/document-2-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_db_btn.setIcon(icon2)
        self.big_db_btn.setIconSize(QtCore.QSize(25, 25))
        self.big_db_btn.setCheckable(True)
        self.big_db_btn.setChecked(True)
        self.big_db_btn.setObjectName("big_db_btn")
        self.gridLayout_3.addWidget(self.big_db_btn, 5, 1, 1, 1)
        self.big_controller_btn = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_controller_btn.setFont(font)
        self.big_controller_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_controller_btn.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/assets/chip-2-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_controller_btn.setIcon(icon3)
        self.big_controller_btn.setIconSize(QtCore.QSize(25, 25))
        self.big_controller_btn.setCheckable(True)
        self.big_controller_btn.setChecked(True)
        self.big_controller_btn.setObjectName("big_controller_btn")
        self.gridLayout_3.addWidget(self.big_controller_btn, 4, 1, 1, 1)
        self.big_insign_bt = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_insign_bt.setFont(font)
        self.big_insign_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_insign_bt.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/assets/box-3-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big_insign_bt.setIcon(icon4)
        self.big_insign_bt.setIconSize(QtCore.QSize(25, 25))
        self.big_insign_bt.setCheckable(True)
        self.big_insign_bt.setChecked(True)
        self.big_insign_bt.setObjectName("big_insign_bt")
        self.gridLayout_3.addWidget(self.big_insign_bt, 3, 1, 1, 1)
        self.big_export_btn = QtWidgets.QPushButton(self.big_menu)
        font = QtGui.QFont()
        font.setFamily("SCG")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.big_export_btn.setFont(font)
        self.big_export_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_export_btn.setStyleSheet("QPushButton {\n"
"    text-align:left;\n"
"   color:white;\n"
"    background-color:    #222222;\n"
"    border-radius: 0px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f44336; /* Darker Red */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Even Darker Red when pressed */\n"
"}\n"
"")
        self.big_export_btn.setIcon(icon4)
        self.big_export_btn.setIconSize(QtCore.QSize(25, 25))
        self.big_export_btn.setCheckable(True)
        self.big_export_btn.setChecked(True)
        self.big_export_btn.setObjectName("big_export_btn")
        self.gridLayout_3.addWidget(self.big_export_btn, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.big_menu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_page.setCurrentIndex(2)
        self.main_page_2.setCurrentIndex(2)
        self.powerOffButton.toggled['bool'].connect(self.powerOnButton.setChecked) # type: ignore
        self.powerOnButton.toggled['bool'].connect(self.powerOffButton.setChecked) # type: ignore
        self.powerOffButton.toggled['bool'].connect(self.powerOnButton.setVisible) # type: ignore
        self.powerOffButton.toggled['bool'].connect(self.powerOffButton.setHidden) # type: ignore
        self.powerOnButton.toggled['bool'].connect(self.powerOffButton.setVisible) # type: ignore
        self.powerOnButton.toggled['bool'].connect(self.powerOnButton.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Controller Board : Erasing & Programming"))
        self.label_5.setText(_translate("MainWindow", "Select Device Type : "))
        self.label_12.setText(_translate("MainWindow", "Serial Port"))
        self.label_13.setText(_translate("MainWindow", "Power"))
        self.label_2.setText(_translate("MainWindow", "___________________________________"))
        self.powerOnButton.setText(_translate("MainWindow", "On"))
        self.powerOffButton.setText(_translate("MainWindow", "Off"))
        self.label_3.setText(_translate("MainWindow", "Device Configuration"))
        self.label_14.setText(_translate("MainWindow", "Lot Number"))
        self.finish_test.setText(_translate("MainWindow", "FINISH"))
        self.clearListButton.setText(_translate("MainWindow", "CLEAR"))
        self.flashButton.setText(_translate("MainWindow", "TEST"))
        self.flashStatusLabel.setText(_translate("MainWindow", "Status : None"))
        self.flashStatusLabel_2.setText(_translate("MainWindow", "Test Result"))
        self.flashStatusLabel_3.setText(_translate("MainWindow", "Lot Detail"))
        self.controller_finder_status.setText(_translate("MainWindow", "Status : None"))
        self.mcu_status.setItemText(0, _translate("MainWindow", "Status"))
        self.mcu_status.setItemText(1, _translate("MainWindow", "Good"))
        self.mcu_status.setItemText(2, _translate("MainWindow", "NG"))
        self.time_frame.setItemText(0, _translate("MainWindow", "Time"))
        self.time_frame.setItemText(1, _translate("MainWindow", "Hour"))
        self.time_frame.setItemText(2, _translate("MainWindow", "Day"))
        self.time_frame.setItemText(3, _translate("MainWindow", "Week"))
        self.time_frame.setItemText(4, _translate("MainWindow", "Month"))
        self.time_frame.setItemText(5, _translate("MainWindow", "Year"))
        self.label_4.setText(_translate("MainWindow", "Controller Board Data"))
        self.device_id_input.setPlaceholderText(_translate("MainWindow", "Device ID"))
        self.device_type.setItemText(0, _translate("MainWindow", "Device Type"))
        self.device_type.setItemText(1, _translate("MainWindow", "Actuator Controller"))
        self.device_type.setItemText(2, _translate("MainWindow", "Sensor Controller"))
        self.label_6.setText(_translate("MainWindow", "Incoming Lot"))
        self.label_18.setText(_translate("MainWindow", "______________________________________________________________________"))
        self.label_30.setText(_translate("MainWindow", "Incoming Devices"))
        self.incom_date.setPlaceholderText(_translate("MainWindow", "L-20XXXXXX-XX"))
        self.income_submit.setText(_translate("MainWindow", "Submit"))
        self.label_32.setText(_translate("MainWindow", "Lot No."))
        self.label_7.setText(_translate("MainWindow", "Controller Board : Erasing & Programming"))
        self.label_8.setText(_translate("MainWindow", "Select Device Type : "))
        self.label_15.setText(_translate("MainWindow", "Serial Port"))
        self.label_16.setText(_translate("MainWindow", "Power"))
        self.label_9.setText(_translate("MainWindow", "___________________________________"))
        self.powerOnButton_2.setText(_translate("MainWindow", "On"))
        self.powerOffButton_2.setText(_translate("MainWindow", "Off"))
        self.label_10.setText(_translate("MainWindow", "Device Configuration"))
        self.label_17.setText(_translate("MainWindow", "Lot Number"))
        self.finish_test_2.setText(_translate("MainWindow", "FINISH"))
        self.clearListButton_2.setText(_translate("MainWindow", "CLEAR"))
        self.flashButton_2.setText(_translate("MainWindow", "TEST"))
        self.flashStatusLabel_4.setText(_translate("MainWindow", "Status : None"))
        self.flashStatusLabel_5.setText(_translate("MainWindow", "Test Result"))
        self.flashStatusLabel_6.setText(_translate("MainWindow", "Lot Detail"))
        self.controller_finder_status_2.setText(_translate("MainWindow", "Status : None"))
        self.mcu_status_2.setItemText(0, _translate("MainWindow", "Status"))
        self.mcu_status_2.setItemText(1, _translate("MainWindow", "Good"))
        self.mcu_status_2.setItemText(2, _translate("MainWindow", "NG"))
        self.time_frame_2.setItemText(0, _translate("MainWindow", "Time"))
        self.time_frame_2.setItemText(1, _translate("MainWindow", "Hour"))
        self.time_frame_2.setItemText(2, _translate("MainWindow", "Day"))
        self.time_frame_2.setItemText(3, _translate("MainWindow", "Week"))
        self.time_frame_2.setItemText(4, _translate("MainWindow", "Month"))
        self.time_frame_2.setItemText(5, _translate("MainWindow", "Year"))
        self.label_11.setText(_translate("MainWindow", "Controller Board Data"))
        self.device_id_input_2.setPlaceholderText(_translate("MainWindow", "Device ID"))
        self.device_type_2.setItemText(0, _translate("MainWindow", "Device Type"))
        self.device_type_2.setItemText(1, _translate("MainWindow", "Actuator Controller"))
        self.device_type_2.setItemText(2, _translate("MainWindow", "Sensor Controller"))
        self.export_document_butt.setText(_translate("MainWindow", "Export"))
        self.label_22.setText(_translate("MainWindow", "______________________________________________________________________"))
        self.label_35.setText(_translate("MainWindow", "Export Result"))
        self.label_37.setText(_translate("MainWindow", "Lot No."))
        self.lot_finder.setPlaceholderText(_translate("MainWindow", "L-20XXXXXX-XX"))
        self.label_19.setText(_translate("MainWindow", "Export Result"))
        self.big_menu_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/assets/SDE-Logo-Login_mini.png\"/></p></body></html>"))
        self.big_db_btn.setText(_translate("MainWindow", " Data Base"))
        self.big_controller_btn.setText(_translate("MainWindow", "  Test"))
        self.big_insign_bt.setText(_translate("MainWindow", "  Setup"))
        self.big_export_btn.setText(_translate("MainWindow", " Export"))
import sde_rc
